# Generated by Django 4.2.29 on 2026-04-26 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(choices=[('walk_in', 'Walk-in'), ('call', 'Phone Call'), ('online', 'Online'), ('referral', 'Referral'), ('other', 'Other')], default='walk_in', max_length=20)),
                ('interests', models.CharField(blank=True, help_text='e.g. Weight loss, Bodybuilding', max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('follow_up', 'Follow-up'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=20)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='branches.branch')),
                ('converted_member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry', to='members.member')),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
